version: "3.9"
services:
  test:
    environment:
      - PYTHONPATH=./src
    image: "my-project"
    volumes:
      - .:/app
    command: python3 -m pytest
    networks: 
      - test-network

networks:
  test-network:
    external: True
